version: '2'
services:
  app:
    build: .
    restart: always
    privileged: true
    volumes:
      - 'config:/config'
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
      - "/dev/mmcblk0:/dev/mmcblk0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
volumes:
  config:

